import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, CheckCircle2, MapPin, Send } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Meta } from '../components/Meta'
import { RichContent } from '../components/RichContent'
import { Layout } from '../components/SiteChrome'
import type { Job, JobQuestion } from '../lib/cms'
import { isSupabaseConfigured, supabase } from '../lib/supabase'

export default function JobPage() {
  const { slug } = useParams(); const [state, setState] = useState<'idle'|'sending'|'sent'>('idle'); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['public-job', slug], enabled: isSupabaseConfigured, queryFn: async () => { const { data, error } = await supabase!.from('jobs').select('*,job_questions(*)').eq('slug', slug!).maybeSingle(); if (error) throw error; return data as (Job & { job_questions: JobQuestion[] }) | null } })
  const job = query.data
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!job) return; setState('sending'); setError(''); const form = new FormData(event.currentTarget); const answers: Record<string, unknown> = {}; for (const question of job.job_questions) { const raw = form.get(`question_${question.id}`); answers[question.id] = question.input_type === 'boolean' ? raw === 'true' : String(raw ?? '') } form.set('jobId', job.id); form.set('answers', JSON.stringify(answers)); const { error: functionError } = await supabase!.functions.invoke('submit-application', { body: form }); if (functionError) { setError(functionError.message); setState('idle') } else { setState('sent'); window.scrollTo({ top: 0, behavior: 'smooth' }) } }
  if (query.isLoading) return <Layout><section className="content-loading">Loading role…</section></Layout>
  if (!job) return <Layout><section className="content-loading"><h1>Role unavailable</h1><Link to="/Routes/careers">View open roles</Link></section></Layout>
  if (state === 'sent') return <Layout><Meta title={`Application received — ${job.title}`} description="Your application has been submitted to Orbit." path={`/careers/${job.slug}`} /><section className="application-success"><CheckCircle2 /><p className="eyebrow">APPLICATION RECEIVED</p><h1>THANK YOU.</h1><p>Your application for {job.title} is now in the Orbit recruiting workspace. The team will review it manually.</p><Link className="button primary" to="/Routes/careers">View other roles</Link></section></Layout>
  return <Layout><Meta title={job.title} description={job.summary} path={`/careers/${job.slug}`} /><section className="job-hero"><Link to="/Routes/careers"><ArrowLeft /> All roles</Link><p className="eyebrow">{job.department.toUpperCase()} / CAREERS</p><h1>{job.title}</h1><p>{job.summary}</p><div><span><MapPin /> {job.location}</span><span>{job.workplace_type}</span><span>{job.employment_type.replace('_',' ')}</span></div></section><div className="job-layout"><article className="job-description"><RichContent document={job.description} /></article><form className="application-form" onSubmit={submit}><p className="eyebrow">APPLY FOR THIS ROLE</p><h2>Your application</h2><label>Full name<input name="fullName" required minLength={2} /></label><label>Email<input name="email" type="email" required /></label><label>Location<input name="location" required /></label><label>LinkedIn URL<input name="linkedinUrl" type="url" /></label><label>Portfolio URL<input name="portfolioUrl" type="url" /></label><label>Cover note<textarea name="coverNote" rows={6} /></label>{job.job_questions.sort((a,b) => a.position-b.position).map(question => <label key={question.id}>{question.prompt}{question.input_type === 'long_text' ? <textarea name={`question_${question.id}`} required={question.required} rows={5} /> : question.input_type === 'select' ? <select name={`question_${question.id}`} required={question.required}><option value="">Select</option>{question.options.map(option => <option key={option}>{option}</option>)}</select> : question.input_type === 'boolean' ? <select name={`question_${question.id}`} required={question.required}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select> : <input name={`question_${question.id}`} required={question.required} />}</label>)}<label>CV (PDF or DOCX, maximum 10 MB)<input name="cv" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required /></label><label className="application-consent"><input type="checkbox" name="consent" value="true" required /><span>I consent to Orbit Systems B.V. processing this application and CV for recruitment. Inactive application data is scheduled for deletion after six months. I can request deletion through support@orbitdev.org.</span></label><input className="application-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" />{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={state === 'sending'}>{state === 'sending' ? 'Submitting…' : <>Submit application <Send /></>}</button></form></div></Layout>
}
