import { Check, ExternalLink } from 'lucide-react'
import { useState } from 'react'
import { Layout, SmartLink } from '../components/SiteChrome'
import { Meta } from '../components/Meta'
import { external } from '../data/siteData'

const plans = [
  { name: 'Developer', monthly: '€0', annual: '€0', note: 'Free for individuals', cta: 'Start Free', href: external.auth, features: ['1,000 tasks per month', 'Standard Orbit model access', 'Single-agent task runner', 'Local file and code analysis', 'Web workspace'] },
  { name: 'Orbit Pro', monthly: '€10 / month', annual: '€100 / year', note: 'For deeper individual work', cta: 'Upgrade to Pro', href: external.billing, popular: true, features: ['Unlimited tasks, subject to fair use', 'Pro Pulsar workspace access', 'Parallel agents, advertised up to 10', 'Browser automation access', 'Windows desktop access', 'Priority inference where available'] },
  { name: 'Orbit Team', monthly: '€25 / user / month', annual: '€250 / user / year', note: 'Planned team capabilities', cta: 'Contact us', href: '/Routes/contact', features: ['Everything in Orbit Pro', 'Shared team context and memory — Planned', 'Centralized administration and billing — Planned', 'Multi-user permissions — Planned', 'Higher workflow limits — Contact us'] },
  { name: 'Enterprise', monthly: 'Custom', annual: 'Custom', note: 'Requirements confirmed with sales', cta: 'Contact Sales', href: '/Routes/contact', features: ['Private deployment discussions', 'Custom model and infrastructure discussions', 'SAML, SCIM, audit, and SLA subject to contract', 'Dedicated technical support direction'] },
]

export default function PricingPage() {
  const [annual, setAnnual] = useState(false)
  return <Layout><Meta title="SIMPLE PLANS. SERIOUS CAPABILITY." description="Orbit AI workspace plans, API request tiers, and credit packs." path="/shop" />
    <section className="pricing-hero"><p className="eyebrow">PLANS / TRANSPARENT ACCESS</p><h1>SIMPLE PLANS.<br />SERIOUS CAPABILITY.</h1><p>Choose workspace access for how you work. API tiers and credit packs are separate and shown below.</p><div className="billing-toggle" role="group" aria-label="Billing period"><button aria-pressed={!annual} onClick={() => setAnnual(false)}>Monthly</button><button aria-pressed={annual} onClick={() => setAnnual(true)}>Annual estimate</button></div>{annual && <small>Annual amounts are estimates. Use the live billing surface to confirm availability and checkout terms.</small>}</section>
    <section className="pricing-grid">{plans.map(plan => <article className={plan.popular ? 'featured' : ''} key={plan.name}>{plan.popular && <span className="plan-label">PRIMARY WORKSPACE PLAN</span>}<h2>{plan.name}</h2><b>{annual ? plan.annual : plan.monthly}</b><p>{plan.note}</p><ul>{plan.features.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul><SmartLink className={`button ${plan.popular ? 'primary' : 'ghost'}`} href={plan.href}>{plan.cta}{plan.href.startsWith('http') && <ExternalLink size={14} />}</SmartLink></article>)}</section>
    <section className="comparison"><p className="section-label">FEATURE COMPARISON</p><div className="comparison-table" role="table" aria-label="Plan comparison"><div role="row"><b role="columnheader">Capability</b>{plans.map(p => <b role="columnheader" key={p.name}>{p.name}</b>)}</div>{[['Web workspace', 'Yes', 'Yes', 'Yes', 'Confirm'], ['Single agent', 'Yes', 'Yes', 'Yes', 'Confirm'], ['Parallel agents', 'No', 'Up to 10 advertised', 'Higher limits', 'Contract'], ['Windows desktop', 'No', 'Yes', 'Yes', 'Contract'], ['Shared context', 'No', 'No', 'Planned', 'Contract'], ['Private deployment', 'No', 'No', 'No', 'Discussion']].map(row => <div role="row" key={row[0]}>{row.map((cell, i) => i ? <span role="cell" key={i}>{cell}</span> : <b role="rowheader" key={i}>{cell}</b>)}</div>)}</div></section>
    <section className="credit-section"><div><p className="section-label">DEVELOPER API</p><h2>Request tiers are separate.</h2><p>Free: 5 requests per minute and 100 per month. Paid: 30 requests per minute and 10,000 per month at the current published access price of €10 one-time. Cost-bearing requests consume one Orbit credit.</p><SmartLink href="/Routes/DEV" className="text-link">Read API documentation</SmartLink></div><div><p className="section-label">CREDIT PACKS</p>{[['Starter', '25 credits', '€4.99'], ['Power', '100 credits', '€14.99'], ['Elite', '500 credits', '€49.99']].map(([name, credits, price]) => <article key={name}><h3>{name}</h3><b>{credits}</b><span>{price}</span></article>)}<p>Credits are currently described in-app as non-expiring.</p></div></section>
    <section className="faq"><p className="section-label">PRICING FAQ</p>{[['Are all Pro tasks unlimited?', 'Orbit Pro is advertised with unlimited tasks subject to fair-use and current service terms. Provider, safety, and operational limits still apply.'], ['Is annual billing live?', 'The annual view is an estimate until the live billing system confirms an annual checkout.'], ['Are Team features available?', 'Some Team capabilities are planned or require direct confirmation. The table labels them accordingly.'], ['Do subscriptions include API usage?', 'Product subscriptions, API request tiers, and credit packs are distinct. Check the developer dashboard for current API access and usage.'], ['Can Enterprise requirements be guaranteed?', 'No. SAML, SCIM, audit, SLA, private deployment, infrastructure, and support requirements are subject to contract and technical confirmation.']].map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}<p className="pricing-change">Pricing and availability may change.</p></section>
  </Layout>
}
