import { zodResolver } from '@hookform/resolvers/zod'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, ExternalLink, Eye, Pencil, Plus, Save, Trash2, Upload, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useForm } from 'react-hook-form'
import { RichTextEditor } from '../../components/RichTextEditor'
import { RichContent } from '../../components/RichContent'
import { editorialSchema, type EditorialPost, type Job, type JobQuestion, type RichNode } from '../../lib/cms'
import { contentMediaUrl, supabase } from '../../lib/supabase'
import { z } from 'zod'

const emptyDoc: RichNode = { type: 'doc', content: [{ type: 'paragraph', content: [] }] }
const toInput = (value?: string | null) => value ? new Date(value).toLocaleString('sv-SE', { timeZone: 'Europe/Berlin' }).replace(' ', 'T').slice(0, 16) : ''
const toUtc = (value: string) => value ? new Date(value).toISOString() : null
const readableError = (error: unknown) => error instanceof Error ? error.message : typeof error === 'object' && error && 'message' in error ? String(error.message) : 'Something went wrong.'

function PageTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) {
  return <div className="admin-page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div>
}
function Status({ value }: { value: string }) { return <span className={`admin-status ${value}`}>{value.replace('_', ' ')}</span> }
function Empty({ children }: { children: React.ReactNode }) { return <p className="admin-empty">{children}</p> }

type EditorialValues = z.infer<typeof editorialSchema>
export function EditorialManager() {
  const client = useQueryClient()
  const [editing, setEditing] = useState<EditorialPost | null>(null)
  const [creating, setCreating] = useState(false)
  const [body, setBody] = useState<RichNode>(emptyDoc)
  const [preview, setPreview] = useState(false)
  const [message, setMessage] = useState('')
  const query = useQuery({ queryKey: ['editorial-admin'], queryFn: async () => { const { data, error } = await supabase!.from('editorial_posts').select('*').order('updated_at', { ascending: false }); if (error) throw error; return data as EditorialPost[] } })
  const defaults: EditorialValues = editing ? { kind: editing.kind, slug: editing.slug, title: editing.title, excerpt: editing.excerpt, author_name: editing.author_name, cover_image_path: editing.cover_image_path ?? '', seo_title: editing.seo_title ?? '', seo_description: editing.seo_description ?? '', status: editing.status as EditorialValues['status'], publish_at: toInput(editing.publish_at), unpublish_at: toInput(editing.unpublish_at) } : { kind: 'blog', slug: '', title: '', excerpt: '', author_name: 'Orbit AI', cover_image_path: '', seo_title: '', seo_description: '', status: 'draft', publish_at: '', unpublish_at: '' }
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<EditorialValues>({ resolver: zodResolver(editorialSchema), values: defaults })
  const openNew = () => { setEditing(null); setBody(emptyDoc); setPreview(false); reset(); setCreating(true); setMessage('') }
  const openEdit = (item: EditorialPost) => { setEditing(item); setBody(item.body); setPreview(false); setCreating(true); setMessage('') }
  const save = handleSubmit(async values => {
    setMessage('')
    const payload = { ...values, body, publish_at: toUtc(values.publish_at ?? ''), unpublish_at: toUtc(values.unpublish_at ?? '') }
    const operation = editing ? supabase!.from('editorial_posts').update(payload).eq('id', editing.id) : supabase!.from('editorial_posts').insert(payload)
    const { error } = await operation
    if (error) { setMessage(error.message); return }
    await client.invalidateQueries({ queryKey: ['editorial-admin'] }); setCreating(false); setEditing(null)
  })
  const remove = async (item: EditorialPost) => { if (!confirm(`Delete “${item.title}”?`)) return; const { error } = await supabase!.from('editorial_posts').delete().eq('id', item.id); if (error) setMessage(error.message); else await client.invalidateQueries({ queryKey: ['editorial-admin'] }) }
  return <section><PageTitle eyebrow="PUBLISHING" title="Writing" action={<button className="admin-primary" onClick={openNew}><Plus /> New post</button>} />
    <div className="admin-filter-row"><span>Blogs, research, and company updates share one publishing workflow.</span></div>
    {message && <p className="admin-error">{message}</p>}
    {creating && <div className="admin-editor-panel"><div className="admin-panel-head"><h2>{editing ? 'Edit post' : 'New post'}</h2><button onClick={() => setCreating(false)} aria-label="Close editor"><X /></button></div><form onSubmit={save} className="admin-form-grid">
      <label>Type<select {...register('kind')}><option value="blog">Blog</option><option value="research">Research</option><option value="product_update">Product update</option></select></label>
      <label>Status<select {...register('status')}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="expired">Expired</option><option value="archived">Archived</option></select></label>
      <label className="full">Title<input {...register('title')} />{errors.title && <small>{errors.title.message}</small>}</label>
      <label className="full">Slug<input {...register('slug')} placeholder="article-url-slug" />{errors.slug && <small>{errors.slug.message}</small>}</label>
      <label className="full">Excerpt<textarea {...register('excerpt')} rows={3} />{errors.excerpt && <small>{errors.excerpt.message}</small>}</label>
      <label>Author<input {...register('author_name')} /></label><span />
      <label className="full">Cover image storage path<input {...register('cover_image_path')} placeholder="2026/image.webp" /></label>
      <label>SEO title<input {...register('seo_title')} /></label><label>SEO description<input {...register('seo_description')} /></label>
      <label>Publish (Berlin)<input type="datetime-local" {...register('publish_at')} required /></label><label>Expire (Berlin)<input type="datetime-local" {...register('unpublish_at')} />{errors.unpublish_at && <small>{errors.unpublish_at.message}</small>}</label>
      <div className="full"><span className="admin-field-label">Content</span><RichTextEditor value={body} onChange={setBody} /><button className="admin-preview-toggle" type="button" onClick={() => setPreview(value => !value)}><Eye /> {preview ? 'Close preview' : 'Preview post'}</button>{preview && <div className="admin-preview"><RichContent document={body} /></div>}</div>
      <div className="full admin-form-actions"><button type="button" onClick={() => setCreating(false)}>Cancel</button><button className="admin-primary" disabled={isSubmitting}><Save /> {isSubmitting ? 'Saving…' : 'Save post'}</button></div>
    </form></div>}
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Publication</th><th /></tr></thead><tbody>{query.data?.map(item => <tr key={item.id}><td><strong>{item.title}</strong><span>/{item.slug}</span></td><td>{item.kind.replace('_', ' ')}</td><td><Status value={item.status} /></td><td>{item.publish_at ? new Date(item.publish_at).toLocaleString('en-GB', { timeZone: 'Europe/Berlin' }) : 'Not scheduled'}</td><td className="admin-actions"><button onClick={() => openEdit(item)} aria-label={`Edit ${item.title}`}><Pencil /></button><button onClick={() => void remove(item)} aria-label={`Delete ${item.title}`}><Trash2 /></button></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.length && <Empty>No posts yet.</Empty>}</div>
  </section>
}

type NoticeRecord = { id: string; kind: string; title: string; message: string; cta_label: string | null; cta_url: string | null; discount_code: string | null; priority: number; status: string; publish_at: string | null; unpublish_at: string | null; countdown_end: string | null }
export function NoticesManager() {
  const client = useQueryClient(); const [current, setCurrent] = useState<NoticeRecord | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['notices-admin'], queryFn: async () => { const { data, error } = await supabase!.from('homepage_notices').select('*').order('priority', { ascending: false }); if (error) throw error; return data as NoticeRecord[] } })
  const edit = (record?: NoticeRecord) => { setCurrent(record ?? null); setOpen(true); setError('') }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const kind = String(fd.get('kind')); const payload = { kind, title: String(fd.get('title')), message: String(fd.get('message')), cta_label: String(fd.get('cta_label')) || null, cta_url: String(fd.get('cta_url')) || null, discount_code: String(fd.get('discount_code')) || null, priority: Number(fd.get('priority')), status: String(fd.get('status')), publish_at: toUtc(String(fd.get('publish_at'))), unpublish_at: toUtc(String(fd.get('unpublish_at'))), countdown_end: kind === 'discount' ? toUtc(String(fd.get('countdown_end'))) : null }; const op = current ? supabase!.from('homepage_notices').update(payload).eq('id', current.id) : supabase!.from('homepage_notices').insert(payload); const { error: saveError } = await op; if (saveError) setError(saveError.message); else { setOpen(false); await client.invalidateQueries({ queryKey: ['notices-admin'] }) } }
  const remove = async (id: string) => { if (!confirm('Delete this homepage notice?')) return; await supabase!.from('homepage_notices').delete().eq('id', id); await client.invalidateQueries({ queryKey: ['notices-admin'] }) }
  return <section><PageTitle eyebrow="HOMEPAGE" title="Announcements & offers" action={<button className="admin-primary" onClick={() => edit()}><Plus /> New notice</button>} />{open && <div className="admin-editor-panel"><div className="admin-panel-head"><h2>{current ? 'Edit notice' : 'New notice'}</h2><button onClick={() => setOpen(false)}><X /></button></div><form className="admin-form-grid" onSubmit={submit}>
    <label>Type<select name="kind" defaultValue={current?.kind ?? 'announcement'}><option value="announcement">Announcement</option><option value="service">Service notice</option><option value="discount">Discount countdown</option></select></label><label>Status<select name="status" defaultValue={current?.status ?? 'draft'}><option>draft</option><option>scheduled</option><option>published</option><option>expired</option><option>archived</option></select></label>
    <label className="full">Title<input name="title" defaultValue={current?.title} required maxLength={120} /></label><label className="full">Message<textarea name="message" defaultValue={current?.message} required maxLength={280} /></label>
    <label>CTA label<input name="cta_label" defaultValue={current?.cta_label ?? ''} /></label><label>CTA URL<input name="cta_url" type="url" defaultValue={current?.cta_url ?? ''} /></label><label>Discount code<input name="discount_code" defaultValue={current?.discount_code ?? ''} /></label><label>Priority<input name="priority" type="number" min="0" max="100" defaultValue={current?.priority ?? 0} /></label>
    <label>Publish (Berlin)<input name="publish_at" type="datetime-local" defaultValue={toInput(current?.publish_at)} required /></label><label>Expire (Berlin)<input name="unpublish_at" type="datetime-local" defaultValue={toInput(current?.unpublish_at)} /></label><label>Countdown end (discounts)<input name="countdown_end" type="datetime-local" defaultValue={toInput(current?.countdown_end)} /></label>
    {error && <p className="admin-error full">{error}</p>}<div className="admin-form-actions full"><button type="button" onClick={() => setOpen(false)}>Cancel</button><button className="admin-primary"><Save /> Save notice</button></div>
  </form></div>}<div className="admin-card-list">{query.data?.map(record => <article key={record.id}><div><span className="admin-kicker">{record.kind} · priority {record.priority}</span><h2>{record.title}</h2><p>{record.message}</p></div><Status value={record.status} /><div className="admin-actions"><button onClick={() => edit(record)}><Pencil /></button><button onClick={() => void remove(record.id)}><Trash2 /></button></div></article>)}</div>{!query.isLoading && !query.data?.length && <Empty>No homepage notices yet.</Empty>}</section>
}

type ServiceRecord = { id: string; title: string; message: string; service_name: string; incident_status: string; severity: string; status: string; publish_at: string | null; resolved_at: string | null }
export function ServiceManager() {
  const client = useQueryClient(); const [current, setCurrent] = useState<ServiceRecord | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['service-admin'], queryFn: async () => { const { data, error } = await supabase!.from('service_updates').select('*').order('publish_at', { ascending: false }); if (error) throw error; return data as ServiceRecord[] } })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const payload = { title: String(fd.get('title')), message: String(fd.get('message')), service_name: String(fd.get('service_name')), incident_status: String(fd.get('incident_status')), severity: String(fd.get('severity')), status: String(fd.get('status')), publish_at: toUtc(String(fd.get('publish_at'))), resolved_at: toUtc(String(fd.get('resolved_at'))) }; const { error: saveError } = await (current ? supabase!.from('service_updates').update(payload).eq('id', current.id) : supabase!.from('service_updates').insert(payload)); if (saveError) setError(saveError.message); else { setOpen(false); setCurrent(null); await client.invalidateQueries({ queryKey: ['service-admin'] }) } }
  return <section><PageTitle eyebrow="NETWORK" title="Service status" action={<button className="admin-primary" onClick={() => { setCurrent(null); setOpen(true) }}><Plus /> New update</button>} />{open && <div className="admin-editor-panel"><form className="admin-form-grid" onSubmit={submit}><label className="full">Title<input name="title" defaultValue={current?.title} required /></label><label className="full">Message<textarea name="message" defaultValue={current?.message} required /></label><label>Service<input name="service_name" defaultValue={current?.service_name ?? 'Orbit AI'} required /></label><label>Incident state<select name="incident_status" defaultValue={current?.incident_status ?? 'investigating'}>{['investigating','identified','monitoring','resolved','maintenance'].map(v => <option key={v}>{v}</option>)}</select></label><label>Severity<select name="severity" defaultValue={current?.severity ?? 'minor'}>{['info','minor','major','critical'].map(v => <option key={v}>{v}</option>)}</select></label><label>Publishing status<select name="status" defaultValue={current?.status ?? 'draft'}>{['draft','scheduled','published','expired','archived'].map(v => <option key={v}>{v}</option>)}</select></label><label>Publish (Berlin)<input name="publish_at" type="datetime-local" defaultValue={toInput(current?.publish_at)} required /></label><label>Resolved (Berlin)<input name="resolved_at" type="datetime-local" defaultValue={toInput(current?.resolved_at)} /></label>{error && <p className="admin-error full">{error}</p>}<div className="admin-form-actions full"><button type="button" onClick={() => setOpen(false)}>Cancel</button><button className="admin-primary"><Save /> Save update</button></div></form></div>}
    <div className="admin-card-list">{query.data?.map(record => <article key={record.id}><div><span className="admin-kicker">{record.service_name} · {record.severity}</span><h2>{record.title}</h2><p>{record.message}</p></div><Status value={record.incident_status} /><div className="admin-actions"><button onClick={() => { setCurrent(record); setOpen(true) }}><Pencil /></button><button onClick={async () => { if (confirm('Delete this service update?')) { await supabase!.from('service_updates').delete().eq('id', record.id); await client.invalidateQueries({ queryKey: ['service-admin'] }) } }}><Trash2 /></button></div></article>)}</div>
  </section>
}

export function JobsManager() {
  const client = useQueryClient(); const [current, setCurrent] = useState<Job | null>(null); const [open, setOpen] = useState(false); const [description, setDescription] = useState<RichNode>(emptyDoc); const [questions, setQuestions] = useState<Partial<JobQuestion>[]>([]); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['jobs-admin'], queryFn: async () => { const { data, error } = await supabase!.from('jobs').select('*,job_questions(*)').order('updated_at', { ascending: false }); if (error) throw error; return data as (Job & { job_questions: JobQuestion[] })[] } })
  const edit = (record?: Job & { job_questions?: JobQuestion[] }) => { setCurrent(record ?? null); setDescription(record?.description ?? emptyDoc); setQuestions((record?.job_questions ?? []).sort((a, b) => a.position - b.position)); setError(''); setOpen(true) }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const fd = new FormData(event.currentTarget); const payload = { slug: String(fd.get('slug')), title: String(fd.get('title')), department: String(fd.get('department')), location: String(fd.get('location')), employment_type: String(fd.get('employment_type')), workplace_type: String(fd.get('workplace_type')), summary: String(fd.get('summary')), description, status: String(fd.get('status')), publish_at: toUtc(String(fd.get('publish_at'))), close_at: toUtc(String(fd.get('close_at'))) }; const result = current ? await supabase!.from('jobs').update(payload).eq('id', current.id).select('id').single() : await supabase!.from('jobs').insert(payload).select('id').single(); if (result.error) { setError(result.error.message); return } const jobId = result.data.id; const invalid = questions.some(q => !q.prompt?.trim() || (q.input_type === 'select' && !(q.options?.length))); if (invalid) { setError('Every screening question needs a prompt, and select questions need options.'); return } if (current) await supabase!.from('job_questions').delete().eq('job_id', jobId); if (questions.length) { const { error: questionError } = await supabase!.from('job_questions').insert(questions.map((q, position) => ({ job_id: jobId, prompt: q.prompt, input_type: q.input_type ?? 'short_text', options: q.options ?? [], required: q.required ?? false, position }))); if (questionError) { setError(questionError.message); return } } setOpen(false); await client.invalidateQueries({ queryKey: ['jobs-admin'] }) }
  const updateQuestion = (index: number, patch: Partial<JobQuestion>) => setQuestions(items => items.map((item, i) => i === index ? { ...item, ...patch } : item))
  return <section><PageTitle eyebrow="CAREERS" title="Jobs" action={<button className="admin-primary" onClick={() => edit()}><Plus /> New role</button>} />{open && <div className="admin-editor-panel"><form className="admin-form-grid" onSubmit={submit}><label className="full">Job title<input name="title" defaultValue={current?.title} required /></label><label>Slug<input name="slug" defaultValue={current?.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label>Department<input name="department" defaultValue={current?.department} required /></label><label>Location<input name="location" defaultValue={current?.location} required /></label><label>Employment<select name="employment_type" defaultValue={current?.employment_type ?? 'full_time'}>{['full_time','part_time','contract','internship','temporary'].map(v => <option key={v}>{v.replace('_',' ')}</option>)}</select></label><label>Workplace<select name="workplace_type" defaultValue={current?.workplace_type ?? 'hybrid'}>{['onsite','hybrid','remote'].map(v => <option key={v}>{v}</option>)}</select></label><label>Status<select name="status" defaultValue={current?.status ?? 'draft'}>{['draft','scheduled','published','expired','archived'].map(v => <option key={v}>{v}</option>)}</select></label><label className="full">Summary<textarea name="summary" defaultValue={current?.summary} required /></label><label>Publish (Berlin)<input name="publish_at" type="datetime-local" defaultValue={toInput(current?.publish_at)} required /></label><label>Close (Berlin)<input name="close_at" type="datetime-local" defaultValue={toInput(current?.close_at)} /></label><div className="full"><span className="admin-field-label">Job description</span><RichTextEditor value={description} onChange={setDescription} /></div>
      <div className="full admin-questions"><div className="admin-panel-head"><h2>Screening questions</h2><button type="button" onClick={() => setQuestions(items => [...items, { prompt: '', input_type: 'short_text', required: false, options: [] }])}><Plus /> Add question</button></div>{questions.map((question, index) => <div className="admin-question" key={question.id ?? index}><input aria-label="Question prompt" value={question.prompt ?? ''} onChange={e => updateQuestion(index, { prompt: e.target.value })} placeholder="Question" /><select aria-label="Answer type" value={question.input_type ?? 'short_text'} onChange={e => updateQuestion(index, { input_type: e.target.value as JobQuestion['input_type'] })}><option value="short_text">Short text</option><option value="long_text">Long text</option><option value="select">Select</option><option value="boolean">Yes / no</option></select>{question.input_type === 'select' && <input aria-label="Options" value={(question.options ?? []).join(', ')} onChange={e => updateQuestion(index, { options: e.target.value.split(',').map(v => v.trim()).filter(Boolean) })} placeholder="Option one, option two" />}<label><input type="checkbox" checked={question.required ?? false} onChange={e => updateQuestion(index, { required: e.target.checked })} /> Required</label><button type="button" onClick={() => setQuestions(items => items.filter((_, i) => i !== index))}><Trash2 /></button></div>)}</div>
      {error && <p className="admin-error full">{error}</p>}<div className="admin-form-actions full"><button type="button" onClick={() => setOpen(false)}>Cancel</button><button className="admin-primary"><Save /> Save role</button></div></form></div>}
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Role</th><th>Location</th><th>Status</th><th>Questions</th><th /></tr></thead><tbody>{query.data?.map(record => <tr key={record.id}><td><strong>{record.title}</strong><span>{record.department}</span></td><td>{record.location} · {record.workplace_type}</td><td><Status value={record.status} /></td><td>{record.job_questions.length}</td><td className="admin-actions"><button onClick={() => edit(record)}><Pencil /></button><button onClick={async () => { if (confirm(`Delete “${record.title}”?`)) { const { error } = await supabase!.from('jobs').delete().eq('id', record.id); if (error) setError(error.message); else await client.invalidateQueries({ queryKey: ['jobs-admin'] }) } }}><Trash2 /></button></td></tr>)}</tbody></table></div>
  </section>
}

type Application = { id: string; full_name: string; email: string; location: string; linkedin_url: string | null; portfolio_url: string | null; cover_note: string | null; cv_path: string; workflow_status: string; internal_notes: string | null; submitted_at: string; retention_delete_at: string; jobs: { title: string } | null; application_answers: { answer: unknown; job_questions: { prompt: string } | null }[] }
export function ApplicationsManager() {
  const client = useQueryClient(); const [selected, setSelected] = useState<Application | null>(null); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['applications-admin'], queryFn: async () => { const { data, error } = await supabase!.from('applications').select('*,jobs(title),application_answers(answer,job_questions(prompt))').order('submitted_at', { ascending: false }); if (error) throw error; return data as unknown as Application[] } })
  const update = async (record: Application, workflow_status: string, internal_notes = record.internal_notes ?? '') => { const { error } = await supabase!.from('applications').update({ workflow_status, internal_notes, last_activity_at: new Date().toISOString(), retention_delete_at: new Date(Date.now() + 183 * 86400000).toISOString() }).eq('id', record.id); if (error) setError(error.message); else { await client.invalidateQueries({ queryKey: ['applications-admin'] }); setSelected(null) } }
  const download = async (path: string) => { const { data, error } = await supabase!.storage.from('candidate-cvs').createSignedUrl(path, 60); if (error) setError(error.message); else window.open(data.signedUrl, '_blank', 'noopener,noreferrer') }
  return <section><PageTitle eyebrow="RECRUITING" title="Applications" />{error && <p className="admin-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Candidate</th><th>Role</th><th>Status</th><th>Received</th><th /></tr></thead><tbody>{query.data?.map(record => <tr key={record.id}><td><strong>{record.full_name}</strong><span>{record.email}</span></td><td>{record.jobs?.title ?? 'Deleted role'}</td><td><Status value={record.workflow_status} /></td><td>{new Date(record.submitted_at).toLocaleDateString('en-GB')}</td><td><button onClick={() => setSelected(record)}>Review</button></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.length && <Empty>No applications yet.</Empty>}</div>
    {selected && <div className="admin-modal-backdrop" onMouseDown={() => setSelected(null)}><div className="admin-modal" onMouseDown={e => e.stopPropagation()}><div className="admin-panel-head"><div><span className="admin-kicker">{selected.jobs?.title}</span><h2>{selected.full_name}</h2></div><button onClick={() => setSelected(null)}><X /></button></div><dl><dt>Email</dt><dd><a href={`mailto:${selected.email}`}>{selected.email}</a></dd><dt>Location</dt><dd>{selected.location}</dd>{selected.linkedin_url && <><dt>LinkedIn</dt><dd><a href={selected.linkedin_url} target="_blank" rel="noreferrer">Open profile <ExternalLink /></a></dd></>}{selected.portfolio_url && <><dt>Portfolio</dt><dd><a href={selected.portfolio_url} target="_blank" rel="noreferrer">Open portfolio <ExternalLink /></a></dd></>}</dl>{selected.cover_note && <div><h3>Cover note</h3><p>{selected.cover_note}</p></div>}{selected.application_answers.length > 0 && <div><h3>Screening answers</h3>{selected.application_answers.map((answer, i) => <p key={i}><strong>{answer.job_questions?.prompt}</strong><br />{String(answer.answer)}</p>)}</div>}<button onClick={() => void download(selected.cv_path)}><Download /> Download CV (60-second link)</button><label>Internal notes<textarea id="application-notes" defaultValue={selected.internal_notes ?? ''} /></label><div className="admin-modal-actions"><select id="application-status" defaultValue={selected.workflow_status}>{['new','reviewing','interview','rejected','hired','withdrawn'].map(v => <option key={v}>{v}</option>)}</select><button className="admin-primary" onClick={() => void update(selected, (document.getElementById('application-status') as HTMLSelectElement).value, (document.getElementById('application-notes') as HTMLTextAreaElement).value)}><Save /> Save review</button><button className="admin-danger" onClick={async () => { if (confirm('Permanently delete this application and CV?')) { await supabase!.storage.from('candidate-cvs').remove([selected.cv_path]); await supabase!.from('applications').delete().eq('id', selected.id); setSelected(null); await client.invalidateQueries({ queryKey: ['applications-admin'] }) } }}><Trash2 /> Delete</button></div></div></div>}
  </section>
}

type MediaAsset = { id: string; storage_path: string; alt_text: string; mime_type: string; size_bytes: number; created_at: string }
export function MediaManager() {
  const client = useQueryClient(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const query = useQuery({ queryKey: ['media-admin'], queryFn: async () => { const { data, error } = await supabase!.from('media_assets').select('*').order('created_at', { ascending: false }); if (error) throw error; return data as MediaAsset[] } })
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); try { const fd = new FormData(event.currentTarget); const file = fd.get('file'); const alt = String(fd.get('alt')); if (!(file instanceof File) || !file.size) throw new Error('Choose an image.'); if (!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type) || file.size > 10 * 1024 * 1024) throw new Error('Use JPG, PNG, WebP, or GIF up to 10 MB.'); const extension = file.name.split('.').pop()?.toLowerCase() ?? 'image'; const path = `${new Date().getUTCFullYear()}/${crypto.randomUUID()}.${extension}`; const { error: uploadError } = await supabase!.storage.from('content-media').upload(path, file, { contentType: file.type }); if (uploadError) throw uploadError; const { error: recordError } = await supabase!.from('media_assets').insert({ storage_path: path, alt_text: alt, mime_type: file.type, size_bytes: file.size }); if (recordError) { await supabase!.storage.from('content-media').remove([path]); throw recordError } event.currentTarget.reset(); await client.invalidateQueries({ queryKey: ['media-admin'] }) } catch (e) { setError(readableError(e)) } finally { setBusy(false) } }
  return <section><PageTitle eyebrow="ASSETS" title="Media library" /><form className="admin-upload" onSubmit={upload}><Upload /><label>Image<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required /></label><label>Alt text<input name="alt" required maxLength={240} /></label><button className="admin-primary" disabled={busy}>{busy ? 'Uploading…' : 'Upload image'}</button></form>{error && <p className="admin-error">{error}</p>}<div className="admin-media-grid">{query.data?.map(asset => <article key={asset.id}><img src={contentMediaUrl(asset.storage_path) ?? ''} alt={asset.alt_text} /><div><strong>{asset.alt_text}</strong><code>{asset.storage_path}</code><button onClick={() => void navigator.clipboard.writeText(contentMediaUrl(asset.storage_path) ?? '')}>Copy public URL</button><button className="admin-danger" onClick={async () => { if (confirm('Delete this image? Existing posts may lose it.')) { await supabase!.storage.from('content-media').remove([asset.storage_path]); await supabase!.from('media_assets').delete().eq('id', asset.id); await client.invalidateQueries({ queryKey: ['media-admin'] }) } }}><Trash2 /></button></div></article>)}</div></section>
}

type AuditEvent = { id: number; actor_id: string | null; action: string; record_type: string; record_id: string | null; before_summary: Record<string, unknown> | null; after_summary: Record<string, unknown> | null; created_at: string }
export function AuditManager() {
  const query = useQuery({ queryKey: ['audit-admin'], queryFn: async () => { const { data, error } = await supabase!.from('audit_events').select('*').order('created_at', { ascending: false }).limit(200); if (error) throw error; return data as AuditEvent[] } })
  return <section><PageTitle eyebrow="SECURITY" title="Audit log" /><div className="admin-card-list audit-list">{query.data?.map(event => <article key={event.id}><div><span className="admin-kicker">{event.action} · {event.record_type}</span><h2>{String(event.after_summary?.title ?? event.before_summary?.title ?? event.record_id ?? 'Record')}</h2><p>{event.actor_id ? `Administrator ${event.actor_id.slice(0, 8)}` : 'System operation'}</p></div><time>{new Date(event.created_at).toLocaleString('en-GB', { timeZone: 'Europe/Berlin' })}</time></article>)}</div>{!query.isLoading && !query.data?.length && <Empty>No audit activity yet.</Empty>}</section>
}
